import { ThemeClasses } from "../theme.config";

export const BASE_STYLES: ThemeClasses = {
  app_header: {
    "highlight-indicator": "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
    "header-gradient":
      "bg-gradient-to-r from-blue-950 via-blue-900 to-blue-950",
    "active-route-indicator": "text-white hover:text-blue-200",
    "inactive-route-indicator": "text-white hover:text-blue-200",
    divider: "bg-blue-800",
    "login-button-bg": "bg-blue-600",
    "login-button-hover": "hover:bg-blue-700",
    "login-button-text": "text-white",
    "header-secondary-gradient": "",
  },
  sports_sidebar: {
    "card-border": "border-gray-300",
    "sport-item-border-l": "border-l-blue-800",
    "category-item-active": "bg-blue-600 text-white",
    "account-icon-active": "text-blue-500",
    "main-bg": "bg-white border border-gray-200",
    "search-bg": "bg-gray-50",
    "search-border": "border-gray-300",
    divider: "bg-gray-200",
    "item-bg": "bg-gray-50",
    "sport-item-border": "border-gray-300",
    "sport-item-bg": "bg-white",
    "sport-item-hover": "hover:bg-gray-50",
    "sport-item-text": "text-slate-700",
    "sport-item-count-bg": "bg-gray-200",
    "sport-item-count-text": "text-slate-600",
    "category-item-bg": "bg-gray-50/50",
    "category-item-border": "border-l-blue-600  border-y-blue-400",
    // "category-item-active": "bg-blue-600", // duplicate removed
    "category-item-hover": "hover:bg-gray-100",
    "category-item-text": "text-slate-700",
    // "account-icon-active": "text-blue-500", // duplicate removed
    "category-item-count-bg": "bg-gray-200",
    "category-item-count-text": "text-slate-500",
    "tournament-item-bg": "bg-white",
    "tournament-item-hover": "hover:bg-blue-50",
    "tournament-item-text": "text-slate-600",
    "tournament-item-count-bg": "bg-gray-100",
    "tournament-item-count-text": "text-slate-500",
    "tournament-item-border": "border-gray-200 ",
  },
  betslip: {
    "main-bg": "bg-white",
    "main-border": "border-slate-300",
    "header-bg": "bg-slate-100",
    divider: "bg-gray-100",
    "tab-bg": "bg-slate-200",
    "tab-border": "border-slate-300",
    "tab-active-bg": "bg-gradient-to-br from-blue-800 to-blue-900",
    "tab-active-text": "text-gray-300",
    "tab-inactive-text": "text-gray-600",
    "outcome-name-text": "text-slate-700 font-bold",
    "slip-item-bg": "bg-white border-slate-300",
    "slip-item-selected-bg": "bg-blue-100 border-blue-300",
    "slip-item-divider": "border-slate-200",
    "slip-item-header": "text-blue-700 font-semibold",
    "slip-item-main": "text-gray-900 font-bold",
    "slip-item-odds": "text-blue-700 font-bold",
    "slip-item-remove": "text-red-400 hover:text-red-600",
    "slip-item-market": "text-gray-500",
    "slip-item-footer": "text-gray-500",
    "multiple-section-bg": "bg-white border-slate-300",
    "combined-section-bg": "bg-white border-slate-300",
    "button-place-bg": "bg-gradient-to-r from-emerald-600 to-green-600",
    "button-place-hover": "hover:from-emerald-700 hover:to-green-700",
    "button-place-text": "text-white",
    "button-confirm-bg": "bg-gradient-to-r from-emerald-600 to-green-600",
    "button-confirm-hover": "hover:from-emerald-700 hover:to-green-700",
    "button-cancel-bg": "bg-gradient-to-r from-red-600 to-red-500",
    "button-cancel-hover": "hover:from-red-700 hover:to-red-600",
  },
  sports_page: {
    // "live-game-indicator": "bg-blue-500", // duplicate removed
    "container-bg": "bg-transparent",
    "card-bg": "bg-white",
    "card-border": "border-gray-300",
    "card-hover": "hover:bg-slate-200/80 hover:border-blue-600/80",
    "header-bg": "bg-gradient-to-r from-blue-950 to-blue-900",
    "header-border": "border-slate-700/50",
    "header-text": "text-gray-100",
    "date-separator-bg": "bg-blue-800",
    "date-separator-text": "text-gray-300",
    "date-separator-border": "border-slate-700/40",
    "time-text": "text-gray-500",
    "time-text-live": "text-green-600",
    "time-border": "border-gray-500",
    "match-tournament-text": "text-gray-500",
    "match-team-text": "text-gray-700",
    "score-text": "text-green-400",
    "more-button-bg": "bg-transparent",
    "more-button-hover": "hover:text-blue-400 hover:border-blue-500/50",
    "more-button-text": "text-gray-600",
    "more-button-border": "border-gray-600",
    "primary-button-bg": "bg-blue-700",
    "primary-button-text": "text-white",
    "secondary-button-bg": "bg-slate-200",
    "secondary-button-text": "text-slate-700",
    "sport-separator-bg": "bg-blue-900",
    "sport-separator-text": "text-gray-200",
    "sport-separator-border": "border-blue-700",
    "skeleton-bg": "bg-gray-600",
    "skeleton-secondary": "bg-slate-800/30",
    "error-text": "text-red-400",
    "error-secondary": "text-gray-400",
    "empty-text": "text-gray-500",
    "empty-secondary": "text-gray-400",
    "live-game-indicator": "bg-blue-500",
  },
  cashdesk_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-white",
    "card-border": "border-slate-700/50",
    "header-bg": "bg-gradient-to-r from-blue-950 via-blue-900 to-blue-950",
    "header-text": "text-white",
    "column-header-bg": "bg-blue-800",
    "column-header-text": "text-slate-300",
    "column-header-border": "border-slate-700/50",
    "row-hover": "hover:bg-slate-900/80",
    "input-bg":
      "bg-gradient-to-r from-slate-50 to-slate-50 placeholder-slate-400 ",
    "input-border":
      "border-slate-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/80 ",
    "input-text": "text-gray-600",
    "summary-section-bg": "bg-gradient-to-r from-white to-gray-50",
    "summary-section-border": "border-blue-500/20",
    "summary-item-bg": "bg-gradient-to-r from-gray-600/10 to-slate-500/20",
    "summary-item-border": "border-gray-300",
    "summary-label-text": "text-gray-500",
    "summary-value-text": "text-gray-700",
    // ...existing code...
    "add-button-bg": "bg-white/20",
    "add-button-hover": "hover:bg-white/30",
    "add-button-border": "border-blue-400",
  },
  bet_list_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-white",
    "card-border": "border-slate-300",
    "card-text": "text-slate-600",
    "column-header-bg": "bg-blue-800",
    "column-header-text": "text-slate-300",
    "row-hover": "hover:bg-slate-100",
    "input-bg": "bg-gradient-to-r from-slate-50 to-slate-50",
    "input-border": "border-slate-400",
    "input-text": "text-gray-600",
    "header-text": "text-gray-900",
    "close-button": "bg-gray-200",
    "close-button-hover": "hover:bg-gray-300",
    "section-bg": "bg-gray-50",
    "section-title": "text-blue-900",
    "label-text": "text-gray-600",
    "value-text": "text-gray-900",
    "item-bg": "bg-white",
    "event-name": "text-gray-900",
    "subtitle-text": "text-gray-500",
    "action-button": "bg-gradient-to-r from-blue-600 to-blue-700",
    "action-button-hover": "hover:from-blue-700 hover:to-blue-800",
    "secondary-button": "bg-gradient-to-r from-slate-500 to-slate-600",
    "secondary-button-hover": "hover:from-slate-600 hover:to-slate-700",
  },

  coupon_details: {
    "section-bg": "bg-gray-50",
    "section-border": "border-gray-200",
    "section-title": "text-blue-900",
    "label-text": "text-gray-600",
    "value-text": "text-gray-900",
    "item-bg": "bg-white",
    "item-border": "border-gray-200",
    "event-name": "text-gray-900",
    "subtitle-text": "text-gray-500",
    divider: "border-gray-200",
    "win-text": "text-green-600",
    "skeleton-bg": "bg-gray-200",
    "skeleton-pulse": "bg-gray-100",
    "action-button": "bg-blue-600",
    "action-button-hover": "hover:bg-blue-700",
    "secondary-button": "bg-gray-500",
    "secondary-button-hover": "hover:bg-gray-600",
  },
  transactions_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-white",
    "card-border": "border-slate-300",

    "card-text": "text-slate-700",
    "column-header-bg": "bg-blue-800",
    "column-header-text": "text-slate-300",
    "row-hover": "hover:bg-slate-100",
    "row-text": "text-gray-700",
    "input-bg": "bg-gradient-to-r from-slate-50 to-slate-50",
    "input-border": "border-slate-300",
    "input-text": "text-gray-600",
    "label-text": "text-gray-600",
    "value-text": "text-gray-700",
    "credit-text": "text-green-600",
    "debit-text": "text-red-600",
    "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
    "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
    "button-primary-text": "text-white",
    "button-secondary-bg": "bg-gradient-to-r from-slate-500 to-slate-600",
    "button-secondary-hover": "hover:from-slate-600 hover:to-slate-700",
    "button-secondary-text": "text-white",
    "checkbox-active-bg": "bg-blue-600",
    "checkbox-active-border": "border-blue-600",
    "checkbox-inactive-border": "border-gray-400",
    "footer-bg": "bg-white",
  },
  deposit_page: {
    "container-bg": "bg-transparent",
    "page-bg": "bg-transparent",
    "page-text": "text-gray-900",
    "header-text": "text-black",
    "warning-bg": "bg-yellow-50",
    "warning-border": "border-yellow-200",
    "warning-icon": "text-yellow-600",
    "warning-text": "text-gray-800",
    "card-bg": "bg-white",
    "card-border": "border-slate-300",
    "table-header-bg": "bg-blue-800",
    "table-header-text": "text-white",
    "row-hover": "hover:bg-slate-100 hover:border-l-blue-600/80",
    "row-text": "text-gray-900",
    "label-text": "text-gray-600",
    "value-text": "text-gray-900",
    "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
    "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
    "button-primary-text": "text-white",
    "button-secondary-bg": "bg-slate-500",
    "button-secondary-hover": "hover:bg-slate-600",
    "button-secondary-text": "text-white",
    "form-bg": "bg-gray-50",
    "form-border": "border-gray-300",
    "form-text": "text-gray-900",
    "info-bg": "bg-gray-100",
    "info-border": "border-gray-300",
    "info-text": "text-gray-700",
    "input-bg": "bg-white",
    "input-border": "border-gray-300",
    "input-text": "text-gray-900",
    "balance-text": "text-gray-600",
    "balance-value": "text-green-600",
    "quick-button-bg": "bg-slate-200",
    "quick-button-hover": "hover:bg-slate-300",
    "quick-button-text": "text-slate-700",
    "quick-button-border": "border-slate-300",
    "security-bg": "bg-blue-50",
    "security-border": "border-blue-200",
    "security-text": "text-blue-700",
  },
  main_input: {
    background: "bg-gradient-to-r from-slate-800 to-slate-700",
    border: "border border-slate-600",
    "text-color": "text-gray-200",
  },
  account_page: {
    "container-bg": "bg-gradient-to-br from-gray-50 via-white to-gray-50",
    "card-bg": "bg-white",
    "card-border": "border-gray-300",
    "header-text": "text-slate-800",
    "subtitle-text": "text-slate-600",
    "section-header-text": "text-slate-700",
    "section-header-border": "border-gray-300",
    "input-bg": "bg-gradient-to-r from-slate-50 to-slate-50",
    "input-border": "border-slate-300 focus:border-blue-500",
    "input-text": "text-gray-600",
    "balance-card-bg": "bg-gradient-to-br from-blue-50/20 to-white",
    "balance-card-border": "border-gray-300",
    "balance-label-text": "text-slate-600",
    "balance-value-text": "text-blue-700",
    "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
    "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
    "button-primary-text": "text-white",
  },
  user_management_page: {
    "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
    "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
    "button-primary-text": "text-white",
    "button-secondary-bg": "bg-gray-200",
    "button-secondary-hover": "hover:bg-gray-300",
    "button-secondary-text": "text-gray-700",
    "page-bg": "bg-gradient-to-br from-gray-50 via-white to-gray-50",
    "page-text": "text-gray-900",
    "header-icon-bg": "bg-blue-100",
    "header-icon-text": "text-blue-600",
    "header-text": "text-gray-900",
    "subtitle-text": "text-gray-600",
    "card-bg": "bg-white",
    "card-border": "border-gray-300",
    "section-header-text": "text-gray-700",
    "section-header-border": "border-gray-300",
    "column-header-bg": "bg-gray-100",
    "column-header-text": "text-gray-700",
    "row-hover": "hover:bg-gray-50",
    "row-text": "text-gray-900",
    "row-border": "border-gray-200",
    "balance-text": "text-emerald-600",
    "input-bg": "bg-white",
    "input-border": "border-gray-300",
    "input-text": "text-gray-900",

    "button-action-deposit-bg": "bg-green-100",
    "button-action-deposit-hover": "hover:bg-green-200",
    "button-action-deposit-text": "text-green-700",
    "button-action-withdraw-bg": "bg-red-100",
    "button-action-withdraw-hover": "hover:bg-red-200",
    "button-action-withdraw-text": "text-red-700",
    "info-card-bg": "bg-gray-50",
    "info-card-border": "border-gray-300",
    "info-label-text": "text-gray-600",
    "info-value-text": "text-gray-900",
    "badge-deposit-bg": "bg-green-100",
    "badge-deposit-text": "text-green-700",
    "badge-withdraw-bg": "bg-red-100",
    "badge-withdraw-text": "text-red-700",
  },
  game_options_modal: {
    "modal-border": "border-gray-300",
    "header-title": "text-slate-800",
    "header-subtitle": "text-slate-600",
    "header-vs-text": "text-blue-600",
    "header-date-text": "text-slate-500",
    "title-text": "text-slate-800",
    "subtitle-text": "text-slate-600",
    "market-card-bg": "bg-white",
    "market-card-border": "border-slate-300",
    "market-card-hover": "hover:border-blue-400 hover:bg-blue-50",
    "market-title": "text-slate-800",
    "axis-label-text": "text-slate-600",
    "axis-label-bg": "bg-slate-200/50",
  },
  modal: {
    change_password: {
      "modal-bg": "bg-white",
      "modal-border": "border-gray-300",
      "modal-shadow": "shadow-gray-500/20",
      "header-border": "border-gray-200",
      "header-title": "text-gray-900",
      "header-icon": "text-blue-600",
      "close-button": "text-gray-500",
      "close-button-hover": "hover:text-gray-900",
      "info-box-bg": "bg-blue-50",
      "info-box-border": "border-blue-200",
      "info-box-text": "text-blue-700",
      "cancel-button-bg": "bg-gray-200",
      "cancel-button-hover": "hover:bg-gray-300",
      "cancel-button-text": "text-gray-900",
      "confirm-button-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
      "confirm-button-hover": "hover:from-blue-500 hover:to-blue-600",
      "confirm-button-text": "text-white",
      "confirm-button-shadow": "shadow-blue-600/25",
    },
    "overlay-bg": "bg-black/30",
    "content-bg": "bg-white",
    "content-border": "border-slate-300",
    "header-bg": "bg-gradient-to-r from-slate-100 to-slate-50",
    "header-text": "text-gray-900",
    "header-border": "border-slate-300",
    "body-bg": "bg-transparent",
    "body-text": "text-gray-900",
    "footer-bg": "bg-slate-50",
    "footer-border": "border-slate-300",
    "close-button": "text-gray-600 hover:text-gray-900",
    "close-button-hover": "hover:bg-gray-200",
  },
  "bg-main": "bg-gradient-to-r from-gray-50 via-white to-slate-50",
  "bg-secondary": "bg-blue-900",
  "bg-tertiary": "bg-blue-800",
  "bg-gradient": "bg-gradient-to-br from-blue-800 to-blue-950",
  "bg-gradient-hover": "hover:from-blue-700 hover:to-blue-900",
  "text-primary": "text-gray-700",
  "text-secondary": "text-gray-600",
  "text-accent": "text-gray-600",
  "text-muted": "text-gray-400",
  "text-link": "text-blue-600",

  "light-divider": "bg-gray-300",
  "dark-divider": "bg-gray-700",
  border: "border-gray-300",
  "border-light": "border-gray-500",
  primary: "text-blue-400",
  "primary-bg": "bg-blue-600",
  "primary-hover": "hover:bg-blue-500/50",
  accent: "text-blue-300",
  "accent-bg": "bg-blue-400",
  "button-primary": "bg-blue-600 hover:bg-blue-500 text-white",
  "button-secondary": "bg-gray-700 hover:bg-gray-600 text-white",
  card: "bg-gray-800/30 border-gray-700/30",
  "card-hover": "hover:border-blue-600/60",
  "item-hover-border-l": "hover:border-l-blue-500/80",
  "card-bg": "bg-[#161616]",
  "input-bg":
    "bg-gradient-to-r from-slate-50 to-slate-50 placeholder-slate-400 ",
  "input-border": "border-slate-300  ",
  "input-focus-within":
    "focus-within:outline-none focus-within:ring-2 focus:outline-none focus:ring-2 focus-within:ring-ring focus-within:ring-offset-0 focus-within:bg-smalltext/10 focus:ring-blue-500/80  focus:ring-2 focus:border-blue-500/80 focus:ring-blue-500/80 focus-within:border-blue-500/80 ",
  "input-ring":
    "outline-none ring-2 ring-blue-500/80 outline-none ring-ring ring-offset-0 bg-smalltext/10 border-blue-500/80",
  "select-option-bg":
    "bg-gradient-to-br from-blue-800 to-blue-900  text-white hover:bg-blue-700/60 hover:to-blue-800/80",
  "select-option-range-bg": "bg-blue-700 text-white hover:bg-blue-700/80",
  "input-text": "text-gray-600",
  "skeleton-bg": "bg-gray-800/30",
  "modal-bg": "bg-slate-50",
  "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
  "button-primary-border": "border border-blue-300",
  "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
  "button-primary-text": "text-white",
  "button-tertiary-bg": "bg-gradient-to-r from-[#1a1a1a] to-[#2a2a2a]",
  "button-tertiary-border": "border border-[#3a3a3a]",
  "button-tertiary-hover": "hover:from-[#2a2a2a] hover:to-[#3a3a3a]",
  "button-tertiary-text": "text-white",
  "button-secondary-bg": "bg-gray-200",
  "button-secondary-border": "border border-gray-300",
  "button-secondary-hover": "hover:bg-gray-300",
  "button-secondary-text": "text-gray-700",
  "button-cancel-bg": "bg-gradient-to-r from-rose-600 to-red-600",
  "button-cancel-hover": "hover:from-rose-700 hover:to-red-700",
  "button-cancel-text": "text-white",
  "button-cancel-border": "border-rose-500/80",
  "button-proceed-bg": "bg-gradient-to-r from-emerald-600 to-green-600",
  "button-proceed-hover": "hover:from-emerald-700 hover:to-green-700",
  "button-proceed-text": "text-white",
  "button-proceed-border": "border-emerald-500",
  "odds-button-bg": "bg-gray-100",
  "odds-button-hover": "hover:bg-blue-300",
  "odds-button-text": "text-slate-800",
  "odds-button-border": "border-slate-300",
  "odds-button-selected-bg":
    "bg-gradient-to-r from-blue-700 via-blue-600 to-blue-700",
  "odds-button-selected-border": "border-blue-500",
  "odds-button-selected-text": "text-white",
  "odds-button-selected-hover": "hover:bg-blue-500",
  "odds-button-disabled-bg": "bg-gray-800/50",
  "odds-button-disabled-text": "text-gray-500",
  "odds-button-disabled-border": "border-gray-700",
};
