import { ThemeClasses } from "../theme.config";

export const BETCRUZ_STYLES: ThemeClasses = {
  app_header: {
    "highlight-indicator": "linear-gradient(135deg, #EA3C00 0%, #FEA352 100%)",
    "header-gradient":
      "bg-gradient-to-r from-[#894824] via-[#884816] to-[#894824]",
    "active-route-indicator": "text-white",
    "inactive-route-indicator": "text-white",
    divider: "bg-[#FEA352]",
    "login-button-bg": "bg-[#EA3C00]",
    "login-button-hover": "hover:bg-[#ea4201]",
    "login-button-text": "text-white",
  },
  sports_sidebar: {
    "card-border": "border-[#EA3C00]/30",
    "sport-item-border-l": "border-l-2 border-[#EA3C00]/30",
    "category-item-active": "bg-[#EA3C00] text-white",
    "account-icon-active": "text-[#884816]",
    "main-bg": "bg-[#ffffff]/70",
    "search-bg": "bg-gradient-to-r from-[#EA3C00] to-[#FEA352]",
    "search-border": "border-[#EA3C00]",
    divider: "bg-[#FEA352]/30",
    "item-bg": "bg-[#FEA352]/30",
    "sport-item-border": "border-[#EA3C00]/30 shadow-lg",
    "sport-item-bg": "bg-[#FCE4BF]/30",
    "sport-item-hover": "hover:bg-[#f99300]/20",
    "sport-item-text": "text-[#884816]",
    "sport-item-count-bg": "bg-[#ea4201]/80",
    "sport-item-count-text": "text-white",
    "category-item-bg": "",
    "category-item-hover": "hover:bg-[#f99300]/30",
    "category-item-text": "text-[#884816]",
    "category-item-border": "border-y-[#EA3C00]/90 border-l-[#EA3C00]",
    "category-item-count-bg": "bg-[#DBD8D4]/40",
    "category-item-count-text": "text-[#ea4201]",
    "tournament-item-bg": "bg-[#FEA352]/20",
    "tournament-item-hover": "hover:bg-[#f99300]/20",
    "tournament-item-text": "text-[#884816]",
    "tournament-item-count-bg": "bg-[#DBD8D4]/30",
    "tournament-item-count-text": "text-[#ea4201]",
    "tournament-item-border": "border-[#FEA352]/10",
  },
  betslip: {
    "main-bg": "bg-[#ffffff]/60",
    "main-border": "border-[#EA3C00]/30",
    "header-bg": "bg-[#FEA352]/50",
    divider: "border-[#EA3C00]/30",
    "tab-bg": "bg-white",
    "tab-border": "border-[#EA3C00]/30",
    "tab-active-bg": "bg-gradient-to-br from-[#EA3C00] to-[#ea4201]",
    "tab-active-text": "text-white",
    "tab-inactive-text": "text-[#ea4201]",
    "outcome-name-text": "text-[#EA3C00] font-bold",
    "slip-item-bg": "bg-[#ffffff]/70 border-[#EA3C0030]",
    "slip-item-selected-bg": "bg-[#ea4201]/30 border-[#EA3C00]/40",
    "slip-item-divider": "border-[#EA3C00]/20",
    "slip-item-header": "text-[#884816] font-semibold",
    "slip-item-main": "text-[#EA3C00] font-bold",
    "slip-item-odds": "text-green-600 font-bold",
    "slip-item-remove": "text-[#ea4201] hover:text-[#EA3C00]",
    "slip-item-market": "text-[#EA3C00]",
    "slip-item-footer": "text-[#ea4201]",
    "multiple-section-bg": "bg-[#FEA352] border-[#EA3C00]/30",
    "combined-section-bg": "bg-[#FEA352] border-[#EA3C00]/30",
    "button-place-bg": "bg-gradient-to-r from-emerald-600 to-green-600",
    "button-place-hover": "hover:from-emerald-700 hover:to-green-700",
    "button-place-text": "text-white",
    "button-confirm-bg": "bg-gradient-to-r from-emerald-600 to-green-600",
    "button-confirm-hover": "hover:from-emerald-700 hover:to-green-700",
    "button-cancel-bg": "bg-gradient-to-r from-[#EA3C00] to-[#ea4201]",
    "button-cancel-hover": "hover:from-[#ea4201] hover:to-[#EA3C00]",
  },
  sports_page: {
    "live-game-indicator": "bg-green-500",
    "container-bg": "bg-transparent",
    "card-bg": "bg-[#ffffff]/90",
    "card-border": "border-[#EA3C00]/20",
    "card-hover": "hover:bg-[#FEA352]/10",
    "header-bg": "bg-gradient-to-r from-[#894824] via-[#884816] to-[#894824]",
    "header-border": "border-[#EA3C00]/50",
    "header-text": "text-[#FCE4BF]",
    "sport-separator-bg": "bg-[#FEA352]/50",
    "sport-separator-text": "text-[#EA3C00]",
    "sport-separator-border": "border-[#EA3C00]/60",
    "date-separator-bg": "bg-[#FEA352]/30",
    "date-separator-text": "text-[#884816]",
    "date-separator-border": "border-[#EA3C00]/40",
    "time-text": "text-[#ea4201]",
    "time-text-live": "text-green-400",
    "time-border": "border-gray-500",
    "match-tournament-text": "text-[#EA3C00]",
    "match-team-text": "text-[#894824]",
    "score-text": "text-green-400",
    "more-button-bg": "bg-transparent",
    "more-button-hover": "hover:text-blue-400 hover:border-blue-500",
    "more-button-text": "text-[#ea4201]",
    "more-button-border": "border-gray-600",
    "primary-button-bg": "bg-[#EA3C00]",
    "primary-button-text": "text-white",
    "secondary-button-bg": "bg-[#FEA352]/40",
    "secondary-button-text": "text-[#EA3C00]",
    "skeleton-bg": "bg-gray-600",
    "skeleton-secondary": "bg-[#FEA352]/30",
    "error-text": "text-[#ea4201]",
    "error-secondary": "text-[#FEA352]",
    "empty-text": "text-[#EA3C00]",
    "empty-secondary": "text-[#ea4201]",
  },
  cashdesk_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-[#FEA352]/20",
    "card-border": "border-[#EA3C00]/30",
    "header-bg": "bg-[#894824]",
    "header-text": "text-[#FCEDCB]",
    "column-header-bg": "bg-[#FEA352]/40",
    "column-header-text": "text-[#884816]",
    "column-header-border": "border-[#EA3C00]/30",
    "row-hover": "hover:bg-[#FEA352]/80",
    "input-bg": "bg-white",
    "input-border": "border-[#EA3C00]/30",
    "input-text": "text-[#884816]",
    "summary-section-bg": "bg-gradient-to-r from-[#DBD8D4]/10 to-[#FEA352]/5",
    "summary-section-border": "border-[#EA3C00]/50",
    "summary-item-bg": "bg-[#FCEDCB]",
    "summary-item-border": "border-[#EA3C00]/30",
    "summary-label-text": "text-[#ea4201]",
    "summary-value-text": "text-[#884816]",
    // ...existing code...
    "add-button-bg": "bg-[#FEA352]/20",
    "add-button-hover": "hover:bg-[#FEA352]/30",
    "add-button-border": "border-[#EA3C00]/50",
  },
  bet_list_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-[#FEA352]/60",
    "card-border": "border-[#EA3C00]/50",
    "card-text": "text-[#ea4201]",
    "column-header-bg": "bg-[#FEA352]/40",
    "column-header-text": "text-[#ea4201]",
    "row-hover": "hover:bg-[#FEA352]/80",
    "input-bg": "bg-gradient-to-r from-[#DBD8D4] to-[#FEA352]",
    "input-border": "border-[#EA3C00]",
    "input-text": "text-[#EA3C00]",
    "header-text": "text-[#ea4201]",
    "close-button": "bg-[#FEA352]/40",
    "close-button-hover": "hover:bg-[#FEA352]/60",
    "section-bg": "bg-[#FEA352]/40",
    "section-title": "text-[#EA3C00]",
    "label-text": "text-[#ea4201]",
    "value-text": "text-[#EA3C00]",
    "item-bg": "bg-[#FEA352]/30",
    "event-name": "text-[#ea4201]",
    "subtitle-text": "text-[#ea4201]",
    "action-button": "bg-gradient-to-r from-[#EA3C00] to-[#ea4201]",
    "action-button-hover": "hover:from-[#ea4201] hover:to-[#EA3C00]",
    "secondary-button": "bg-gradient-to-r from-[#FEA352] to-[#DBD8D4]",
    "secondary-button-hover": "hover:from-[#f99300] hover:to-[#EA3C00]",
  },
  modal: {
    change_password: {
      "modal-bg": "bg-[#DBD8D4]",
      "modal-border": "border-[#EA3C00]",
      "modal-shadow": "shadow-[#EA3C00]/50",
      "header-border": "border-[#EA3C00]/50",
      "header-title": "text-[#EA3C00]",
      "header-icon": "text-[#ea4201]",
      "close-button": "text-[#ea4201]",
      "close-button-hover": "hover:text-[#EA3C00]",
      "info-box-bg": "bg-[#FEA352]/10",
      "info-box-border": "border-[#FEA352]/20",
      "info-box-text": "text-[#ea4201]",
      "cancel-button-bg": "bg-[#FEA352]",
      "cancel-button-hover": "hover:bg-[#f99300]",
      "cancel-button-text": "text-[#EA3C00]",
      "confirm-button-bg": "bg-gradient-to-r from-[#EA3C00] to-[#ea4201]",
      "confirm-button-hover": "hover:from-[#ea4201] hover:to-[#EA3C00]",
      "confirm-button-text": "text-white",
      "confirm-button-shadow": "shadow-[#EA3C00]/25",
    },
    "overlay-bg": "bg-black/50",
    "content-bg": "bg-[#DBD8D4]",
    "content-border": "border-[#EA3C00]/30",
    "header-bg": "bg-gradient-to-r from-[#EA3C00] to-[#FEA352]",
    "header-text": "text-[#EA3C00]",
    "header-border": "border-[#EA3C00]/30",
    "body-bg": "bg-transparent",
    "body-text": "text-[#ea4201]",
    "footer-bg": "bg-[#FEA352]/30",
    "footer-border": "border-[#EA3C00]/30",
    "close-button": "text-[#ea4201] hover:text-[#EA3C00]",
    "close-button-hover": "hover:bg-[#FEA352]/40",
  },
  coupon_details: {
    "section-bg": "bg-[#FEA352]/40",
    "section-border": "border-[#EA3C00]/30",
    "section-title": "text-[#EA3C00]",
    "label-text": "text-[#ea4201]",
    "value-text": "text-[#EA3C00]",
    "item-bg": "bg-[#FEA352]/30",
    "item-border": "border-[#EA3C00]/20",
    "event-name": "text-[#ea4201]",
    "subtitle-text": "text-[#ea4201]",
    divider: "border-[#EA3C00]/30",
    "win-text": "text-green-500",
    "skeleton-bg": "bg-[#FEA352]/20",
    "skeleton-pulse": "bg-[#FEA352]/30",
    "action-button": "bg-gradient-to-r from-[#EA3C00] to-[#ea4201]",
    "action-button-hover": "hover:from-[#ea4201] hover:to-[#EA3C00]",
    "secondary-button": "bg-gradient-to-r from-[#FEA352] to-[#DBD8D4]",
    "secondary-button-hover": "hover:from-[#f99300] hover:to-[#EA3C00]",
  },
  transactions_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-[#FEA352]/60",
    "card-border": "border-[#EA3C00]/30",

    "card-text": "text-[#ea4201]",
    "column-header-bg": "bg-[#FEA352]/40",
    "column-header-text": "!text-[#FCE4BF]",
    "row-hover": "hover:bg-[#FEA352]/20",
    "row-text": "text-[#884816]",
    "input-bg": "bg-gradient-to-r from-[#DBD8D4] to-[#FEA352]",
    "input-border": "border-[#EA3C00]",
    "input-text": "text-[#EA3C00]",
    "label-text": "text-[#ea4201]",
    "value-text": "text-[#EA3C00]",
    "credit-text": "text-green-500",
    "debit-text": "text-red-500",
    "button-primary-bg": "bg-gradient-to-r from-[#EA3C00] to-[#ea4201]",
    "button-primary-hover": "hover:from-[#ea4201] hover:to-[#EA3C00]",
    "button-primary-text": "text-white",
    "button-secondary-bg": "bg-gradient-to-r from-[#FEA352] to-[#DBD8D4]",
    "button-secondary-hover": "hover:from-[#f99300] hover:to-[#EA3C00]",
    "button-secondary-text": "text-[#EA3C00]",
    "checkbox-active-bg": "bg-[#EA3C00]",
    "checkbox-active-border": "border-[#EA3C00]",
    "checkbox-inactive-border": "border-[#FEA352]",
    "footer-bg": "bg-[#FEA352]/30",
  },
  deposit_page: {
    "container-bg": "bg-transparent",

    "page-bg": "bg-transparent",
    "page-text": "text-[#EA3C00]",
    "header-text": "text-black",
    "warning-bg": "bg-yellow-100",
    "warning-border": "border-yellow-300",
    "warning-icon": "text-yellow-600",
    "warning-text": "text-[#884816]",
    "card-bg": "bg-[#FEA352]/60",
    "card-border": "border-[#EA3C00]/50",
    "table-header-bg": "bg-[#FEA352]/40",
    "table-header-text": "text-[#ea4201]",
    "row-hover": "hover:bg-[#FEA352]/80",
    "row-text": "text-[#EA3C00]",
    "label-text": "text-[#ea4201]",
    "value-text": "text-[#EA3C00]",
    "button-primary-bg": "bg-gradient-to-r from-[#EA3C00] to-[#ea4201]",

    "button-primary-hover": "hover:from-[#ea4201] hover:to-[#EA3C00]",
    "button-primary-text": "text-white",
    "button-secondary-bg": "bg-gradient-to-r from-[#FEA352] to-[#DBD8D4]",
    "button-secondary-hover": "hover:from-[#f99300] hover:to-[#EA3C00]",
    "button-secondary-text": "text-[#EA3C00]",
    "form-bg": "bg-[#884816]",

    "form-border": "border-[#EA3C00]/30",
    "form-text": "text-[#FCEDCB]",
    "info-bg": "bg-[#FEA352]/20",
    "info-border": "border-[#EA3C00]/40",
    "info-text": "text-[#ea4201]",
    "input-bg": "bg-gradient-to-r from-[#DBD8D4] to-[#FEA352]",
    "input-border": "border-[#EA3C00]",
    "input-text": "text-[#EA3C00]",
    "balance-text": "text-[#ea4201]",
    "balance-value": "text-green-500",
    "quick-button-bg": "bg-[#FEA352]/20",
    "quick-button-hover": "hover:bg-[#FEA352]/40",
    "quick-button-text": "text-[#EA3C00]",
    "quick-button-border": "border-[#EA3C00]/30",
    "security-bg": "bg-[#EA3C00]/10",
    "security-border": "border-[#EA3C00]/20",
    "security-text": "text-[#ea4201]",
  },
  game_options_modal: {
    "modal-border": "border-[#EA3C00]/40",
    "header-title": "text-[#884816]",
    "header-subtitle": "text-[#ea4201]",
    "header-vs-text": "text-[#EA3C00]",
    "header-date-text": "text-[#ea4201]",
    "title-text": "text-[#EA3C00]",
    "subtitle-text": "text-[#ea4201]",
    "market-card-bg": "bg-[#FCE4BF]/50",
    "market-card-border": "border-[#EA3C00]/20",
    "market-card-hover": "hover:border-[#EA3C00]/20 hover:bg-[#FEA352]/5",
    "market-title": "text-[#884816]",
    "axis-label-text": "text-[#EA3C00]",
    "axis-label-bg": "bg-[#EA3C00]/20",
  },
  main_input: {
    background: "bg-gradient-to-r from-[#FEA352] to-[#DBD8D4]",
    border: "border border-[#EA3C00]",
    "text-color": "text-[#EA3C00]",
  },
  account_page: {
    "container-bg": "bg-gradient-to-br from-gray-50 via-white to-gray-50",
    "card-bg": "bg-white",
    "card-border": "border-gray-300",
    "header-text": "text-slate-800",
    "subtitle-text": "text-slate-600",
    "section-header-text": "text-slate-700",
    "section-header-border": "border-gray-300",
    "input-bg": "bg-gradient-to-r from-slate-50 to-slate-50",
    "input-border": "border-slate-300 focus:border-blue-500",
    "input-text": "text-gray-600",
    "balance-card-bg": "bg-gradient-to-br from-blue-50/20 to-white",
    "balance-card-border": "border-[#EA3C00]/20",
    "balance-label-text": "text-slate-600",
    "balance-value-text": "text-blue-700",
    "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
    "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
    "button-primary-text": "text-white",
  },
  user_management_page: {
    "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
    "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
    "button-primary-text": "text-white",
    "button-secondary-bg": "bg-gray-200",
    "button-secondary-hover": "hover:bg-gray-300",
    "button-secondary-text": "text-gray-700",
    "page-bg": "bg-gradient-to-br from-gray-50 via-white to-gray-50",
    "page-text": "text-gray-900",
    "header-icon-bg": "bg-[#88481630]",
    "header-icon-text": "text-blue-600",
    "header-text": "text-gray-900",
    "subtitle-text": "text-gray-600",
    "card-bg": "bg-white",
    "card-border": "border-gray-300",
    "section-header-text": "text-gray-700",
    "section-header-border": "border-gray-300",
    "column-header-bg": "bg-gray-100",
    "column-header-text": "text-gray-700",
    "row-hover": "hover:bg-gray-50",
    "row-text": "text-gray-900",
    "row-border": "border-gray-200",
    "balance-text": "text-emerald-600",
    "input-bg": "bg-white",
    "input-border": "border-gray-300",
    "input-text": "text-gray-900",

    "button-action-deposit-bg": "bg-green-100",
    "button-action-deposit-hover": "hover:bg-green-200",
    "button-action-deposit-text": "text-green-700",
    "button-action-withdraw-bg": "bg-red-100",
    "button-action-withdraw-hover": "hover:bg-red-200",
    "button-action-withdraw-text": "text-red-700",
    "info-card-bg": "bg-gray-50",
    "info-card-border": "border-gray-300",
    "info-label-text": "text-gray-600",
    "info-value-text": "text-gray-900",
    "badge-deposit-bg": "bg-green-100",
    "badge-deposit-text": "text-green-700",
    "badge-withdraw-bg": "bg-red-100",
    "badge-withdraw-text": "text-red-700",
  },
  "bg-main": "bg-white",
  "bg-secondary": "bg-[#FEA352]",
  "bg-tertiary": "bg-[#EA3C00]",
  "bg-gradient": "bg-gradient-to-br from-blue-800 to-blue-950",
  "bg-gradient-hover": "hover:from-blue-700 hover:to-blue-900",
  "text-primary": "text-[#884816]",
  "text-secondary": "text-[#884816]/70",
  "text-accent": "text-[#884816]/70",
  "text-muted": "text-gray-400",
  "text-link": "text-blue-400",
  "light-divider": "bg-gray-300",
  "dark-divider": "bg-gray-700",
  border: "border-[#EA3C00]/30",
  "border-light": "border-gray-500",
  primary: "text-blue-400",
  "primary-bg": "bg-blue-600",
  "primary-hover": "hover:bg-[#88481650]",
  accent: "text-blue-300",
  "accent-bg": "bg-blue-400",
  "card-bg": "bg-[#DBD8D4]",
  card: "bg-gray-800/30 border-gray-700/30",
  "card-hover": "hover:border-blue-600/60",
  "input-focus-within":
    "focus-within:outline-none focus-within:ring-2 focus:outline-none focus:ring-2 focus-within:ring-ring focus-within:ring-offset-0 focus-within:bg-[#FEA352]/10 focus:ring-[#EA3C00]/80 focus:ring-2 focus:border-[#EA3C00]/80 focus-within:border-[#EA3C00]/80 ",
  "input-ring":
    "outline-none ring-2 ring-[#EA3C00]/80 outline-none ring-ring ring-offset-0 bg-[#FEA352]/10 border-[#EA3C00]/80",
  "select-option-bg":
    "bg-gradient-to-br from-[#EA3C00] to-[#f99300] text-white hover:bg-[#f99300]/80 hover:to-[#EA3C00]/80",
  "select-option-range-bg": "bg-[#f99300]/90 text-white hover:bg-[#EA3C00]/60",
  "item-hover-border-l": "hover:border-l-[#EA3C00]/60",
  "input-bg":
    "bg-gradient-to-r from-slate-50 to-slate-50 placeholder-slate-400 ",
  "input-border": "border-[#EA3C00]/30",

  // "input-focus-within":
  //   "focus-within:outline-none focus-within:ring-2 focus:outline-none focus:ring-2 focus-within:ring-ring focus-within:ring-offset-0 focus-within:bg-smalltext/10 focus:ring-blue-500/80  focus:ring-2 focus:border-blue-500/80 focus:ring-blue-500/80 focus-within:border-blue-500/80 ",
  // "input-ring":
  //   "outline-none ring-2 ring-blue-500/80 outline-none ring-ring ring-offset-0 bg-smalltext/10 border-blue-500/80",
  // "select-option-bg":
  // "bg-gradient-to-br from-blue-800 to-blue-900  text-white",
  "input-text": "text-[#884816] placeholder-[#88481680] ",
  "modal-bg": "bg-[#ffffff]",
  "button-primary": "bg-blue-600 hover:bg-blue-500 text-white",
  "button-secondary": "bg-gray-700 hover:bg-gray-600 text-white",
  "button-primary-bg": "bg-gradient-to-r from-blue-600 to-blue-700",
  "button-primary-border": "border border-blue-300",
  "button-primary-hover": "hover:from-blue-700 hover:to-blue-800",
  "button-primary-text": "text-white",
  "button-secondary-bg": "bg-gray-200",
  "button-secondary-border": "border border-gray-300",
  "button-secondary-hover": "hover:bg-gray-300",
  "button-secondary-text": "text-gray-700",
  "button-tertiary-bg": "bg-gradient-to-r from-[#1a1a1a] to-[#2a2a2a]",
  "button-tertiary-border": "border border-[#3a3a3a]",
  "button-tertiary-hover": "hover:from-[#2a2a2a] hover:to-[#3a3a3a]",
  "button-tertiary-text": "text-white",
  "button-cancel-bg": "bg-gradient-to-r from-rose-600 to-red-600",
  "button-cancel-hover": "hover:from-rose-700 hover:to-red-700",
  "button-cancel-text": "text-white",
  "button-cancel-border": "border-rose-500/80",
  "button-proceed-bg": "bg-gradient-to-r from-emerald-600 to-green-600",
  "button-proceed-hover": "hover:from-emerald-700 hover:to-green-700",
  "button-proceed-text": "text-white",
  "button-proceed-border": "border-emerald-500",
  "skeleton-bg": "bg-[#894824]/20",
  "odds-button-bg": "bg-white",
  "odds-button-hover": "hover:bg-[#ffcfab]",
  "odds-button-text": "text-[#884816]",
  "odds-button-border": "border-[#884816]/30",
  "odds-button-selected-bg":
    "bg-gradient-to-r from-[#EA3C00] via-[#ea4201]/90 to-[#EA3C00]",
  "odds-button-selected-border": "border-[#EA3C00]/40",
  "odds-button-selected-text": "text-white",
  "odds-button-selected-hover": "hover:bg-[#f99300]/40",
  "odds-button-disabled-bg": "bg-gray-400/50",
  "odds-button-disabled-text": "text-gray-700",
  "odds-button-disabled-border": "border-gray-400",
};
