import { ThemeClasses } from "../theme.config";

export const MAXBET_STYLES: ThemeClasses = {
  app_header: {
    "highlight-indicator":
      "linear-gradient(90deg,rgba(17, 18, 18, 1) 0%, rgba(41, 13, 13, 1) 35%, rgba(5, 0, 0, 1) 76%, rgba(41, 7, 7, 1) 100%)",
    "header-gradient": "bg-gradient-to-r from-red-950 via-rose-900 to-red-950",
    "active-route-indicator": "text-white hover:text-rose-100",
    "inactive-route-indicator": "text-white hover:text-rose-200",
    divider: "bg-red-800",
    "login-button-bg": "bg-red-600",
    "login-button-hover": "hover:bg-red-700",
    "login-button-text": "text-white",
    "header-secondary-gradient": "",
  },
  sports_sidebar: {
    "main-bg": "bg-[#161616]",
    "card-border": "border-yellow-700/30",
    "sport-item-border-l": "border-l-yellow-600/70",
    "category-item-active": "bg-yellow-600 text-black",
    "account-icon-active": "text-yellow-500",
    "search-bg": "bg-gradient-to-r from-gray-950 to-black",
    "search-border": "border-yellow-700/40",
    divider: "bg-yellow-700/20",
    "item-bg": "bg-gray-900/30",
    "sport-item-border": "border-yellow-600/20",
    "sport-item-bg": "bg-transparent",
    "sport-item-hover": "hover:bg-[#450A0A]/30",
    "sport-item-text": "text-yellow-100",
    "sport-item-count-bg": "bg-gray-700/50",
    "sport-item-count-text": "text-yellow-300",
    "category-item-bg": "bg-[#161616]",
    "category-item-hover": "hover:bg-[#450A0A]/30",
    "category-item-text": "text-gray-300",
    "category-item-border": "border-yellow-600/60 border-l-yellow-600/80",
    "category-item-count-bg": "bg-gray-600/50",
    "category-item-count-text": "text-gray-400",
    "tournament-item-bg": "bg-[#161616]",
    "tournament-item-hover": "hover:bg-red-800/20",
    "tournament-item-text": "text-gray-300",
    "tournament-item-count-bg": "bg-gray-600/30",
    "tournament-item-count-text": "text-gray-500",
    "tournament-item-border": "border-gray-600/10",
  },
  betslip: {
    "main-bg": "bg-gradient-to-b from-black to-gray-950",
    "main-border": "border-yellow-700/40",
    "header-bg": "bg-[#161616]",
    divider: "bg-yellow-700/40",
    "tab-bg": "bg-[#161616]",
    "tab-border": "border-yellow-700/40",
    "tab-active-bg": "bg-gradient-to-br from-yellow-500 to-yellow-700",
    "tab-active-text": "text-black",
    "tab-inactive-text": "text-gray-400",
    "outcome-name-text": "text-yellow-400 font-bold",
    "slip-item-bg": "bg-[#161616] border-yellow-700/20",
    "slip-item-selected-bg": "bg-yellow-900/20 border-yellow-600/40",
    "slip-item-divider": "border-yellow-700/20",
    "slip-item-header": "text-yellow-300 font-semibold",
    "slip-item-main": "text-white font-bold",
    "slip-item-odds": "text-yellow-400 font-bold",
    "slip-item-remove": "text-red-400 hover:text-red-600",
    "slip-item-market": "text-gray-400",
    "slip-item-footer": "text-gray-400",
    "multiple-section-bg": "bg-[#161616] border-yellow-700/30",
    "combined-section-bg": "bg-[#161616] border-yellow-700/30",
    "button-place-bg": "bg-gradient-to-r from-yellow-600 to-yellow-500",
    "button-place-hover": "hover:from-yellow-700 hover:to-yellow-600",
    "button-place-text": "text-black",
    "button-confirm-bg": "bg-gradient-to-r from-yellow-600 to-yellow-500",
    "button-confirm-hover": "hover:from-yellow-700 hover:to-yellow-600",
    "button-cancel-bg": "bg-gradient-to-r from-red-600 to-red-500",
    "button-cancel-hover": "hover:from-red-700 hover:to-red-600",
  },
  sports_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-[#161616]",
    "card-border": "border-yellow-700/30",
    "card-hover": "hover:bg-red-800/20",
    "header-bg":
      "bg-gradient-to-r from-[#450A0A]/60 via-[#450A0A]/80 to-[#7F1D1D]/40",
    "header-border": "border-yellow-700/30",
    "header-text": "text-yellow-200",
    "sport-separator-bg": "bg-gray-900/50",
    "sport-separator-text": "text-yellow-100",
    "sport-separator-border": "border-yellow-700/40",
    "date-separator-bg": "bg-red-900/40",

    "date-separator-text": "text-yellow-100",
    "date-separator-border": "border-yellow-700/30",
    "time-text": "text-gray-300",
    "time-text-live": "text-green-400",
    "time-border": "border-gray-500",
    "match-tournament-text": "text-gray-400",
    "match-team-text": "text-white",
    "score-text": "text-green-400",
    "more-button-bg": "bg-transparent",
    "more-button-hover": "hover:text-yellow-400 hover:border-yellow-500",
    "more-button-text": "text-gray-300",
    "more-button-border": "border-gray-600",
    "primary-button-bg": "bg-yellow-600",
    "primary-button-text": "text-black",
    "secondary-button-bg": "bg-gray-800/40",
    "secondary-button-text": "text-yellow-200",
    "skeleton-bg": "bg-gray-600",
    "skeleton-secondary": "bg-gray-900/30",
    "error-text": "text-red-400",
    "error-secondary": "text-gray-400",
    "empty-text": "text-yellow-300",
    "empty-secondary": "text-gray-400",
    "live-game-indicator": "bg-yellow-500",
  },
  cashdesk_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-[#161616]",
    "card-border": "border-yellow-700/30",
    "header-bg":
      "bg-gradient-to-r from-[#450A0A]/60 via-[#450A0A]/80 to-[#7F1D1D]/40",
    "header-text": "text-yellow-200",
    "column-header-bg": "bg-red-900/40",
    "column-header-text": "text-yellow-100",
    "column-header-border": "border-yellow-700/30",
    "row-hover": "hover:bg-black/80",
    "input-bg":
      "bg-gradient-to-r from-slate-50 to-slate-50 placeholder-slate-400 ",
    "input-border":
      "border-slate-400 focus:border-blue-500 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary",
    "input-text": "text-gray-600",
    "summary-section-bg": "bg-[#161616]",
    "summary-section-border": "border-yellow-700/30",
    "summary-item-bg": "bg-gradient-to-r from-gray-600/20 to-slate-500/30",
    "summary-item-border": "border-gray-700/50",
    "summary-label-text": "text-gray-300",
    "summary-value-text": "text-gray-400",
    // ...existing code...
    "add-button-bg": "bg-white/20",
    "add-button-hover": "hover:bg-white/30",
    "add-button-border": "border-yellow-400",
  },
  bet_list_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-black/60",
    "card-border": "border-yellow-700/30",
    "card-text": "text-slate-200",
    "column-header-bg":
      "bg-gradient-to-r from-[#450A0A]/60 via-[#450A0A]/80 to-[#7F1D1D]/40",
    "column-header-text": "text-yellow-100",
    "row-hover": "hover:bg-black/80",
    "input-bg": "bg-gradient-to-r from-gray-950 to-slate-950",
    "input-border": "border-slate-800",
    "input-text": "text-white",
    "header-text": "text-slate-200",
    "close-button": "bg-gray-900/40",
    "close-button-hover": "hover:bg-gray-800/60",
    "section-bg": "bg-black/40",
    "section-title": "text-yellow-300",
    "label-text": "text-gray-400",
    "value-text": "text-gray-300",
    "item-bg": "bg-gray-900/30",
    "event-name": "text-slate-200",
    "subtitle-text": "text-gray-400",
    "action-button": "bg-gradient-to-r from-yellow-600 to-yellow-500",
    "action-button-hover": "hover:from-yellow-700 hover:to-yellow-600",
    "secondary-button": "bg-gradient-to-r from-slate-700 to-slate-800",
    "secondary-button-hover": "hover:from-slate-800 hover:to-slate-900",
  },

  coupon_details: {
    "section-bg": "bg-black/40",
    "section-border": "border-yellow-700/30",
    "section-title": "text-yellow-200",
    "label-text": "text-gray-400",
    "value-text": "text-gray-300",
    "item-bg": "bg-gray-900/30",
    "item-border": "border-yellow-700/20",
    "event-name": "text-slate-200",
    "subtitle-text": "text-gray-400",
    divider: "border-yellow-700/30",
    "win-text": "text-green-500",
    "skeleton-bg": "bg-gray-700/50",
    "skeleton-pulse": "bg-gray-700/30",
    "action-button": "bg-yellow-600",
    "action-button-hover": "hover:bg-yellow-700",
    "secondary-button": "bg-yellow-800/50",
    "secondary-button-hover": "hover:bg-yellow-800",
  },
  transactions_page: {
    "container-bg": "bg-transparent",
    "card-bg": "bg-black/60",
    "card-border": "border-yellow-700/30 ",
    "card-text": "text-yellow-200",
    "column-header-bg": "bg-gray-900/40",
    "column-header-text": "text-yellow-200",
    "row-hover": "hover:bg-red-800/20",
    "row-text": "text-yellow-50",
    "input-bg": "bg-gradient-to-r from-gray-950 to-slate-950",
    "input-border": "border-slate-800",
    "input-text": "text-white",
    "label-text": "text-gray-400",
    "value-text": "text-gray-300",
    "credit-text": "text-green-500",
    "debit-text": "text-red-500",
    "button-primary-bg": "bg-gradient-to-r from-yellow-600 to-yellow-500",
    "button-primary-hover": "hover:from-yellow-700 hover:to-yellow-600",
    "button-primary-text": "text-black",
    "button-secondary-bg": "bg-gradient-to-r from-slate-700 to-slate-800",
    "button-secondary-hover": "hover:from-slate-800 hover:to-slate-900",
    "button-secondary-text": "text-white",
    "checkbox-active-bg": "bg-yellow-600",
    "checkbox-active-border": "border-yellow-600",
    "checkbox-inactive-border": "border-gray-400",
    "footer-bg": "bg-gray-900/40",
  },
  deposit_page: {
    "container-bg": "bg-transparent",
    "page-bg": "bg-transparent",
    "page-text": "text-white",
    "header-text": "text-yellow-100",
    "warning-bg": "bg-yellow-50",
    "warning-border": "border-yellow-200",
    "warning-icon": "text-yellow-600",
    "warning-text": "text-gray-800",
    "card-bg": "bg-black/60",
    "card-border": "border-yellow-700/30",
    "table-header-bg": "bg-gray-900/40",
    "table-header-text": "text-white",
    "row-hover": "hover:bg-black/80",
    "row-text": "text-white",
    "label-text": "text-gray-400",
    "value-text": "text-white",
    "button-primary-bg": "bg-gradient-to-r from-yellow-600 to-yellow-500",
    "button-primary-hover": "hover:from-yellow-700 hover:to-yellow-600",
    "button-primary-text": "text-black",
    "button-secondary-bg": "bg-slate-700",
    "button-secondary-hover": "hover:bg-slate-600",
    "button-secondary-text": "text-white",
    "form-bg": "bg-gray-800/50",
    "form-border": "border-gray-700/30",
    "form-text": "text-white",
    "info-bg": "bg-red-900/30",
    "info-border": "border-yellow-800/30",
    "info-text": "text-gray-300",
    "input-bg": "bg-gradient-to-r from-gray-950 to-slate-950",
    "input-border": "border-slate-800",
    "input-text": "text-white",
    "balance-text": "text-gray-400",
    "balance-value": "text-green-400",
    "quick-button-bg": "bg-red-900/30",
    "quick-button-hover": "hover:bg-red-800/40",
    "quick-button-text": "text-yellow-200/60",
    "quick-button-border": "border-yellow-800/40",
    "security-bg": "bg-blue-500/10",
    "security-border": "border-blue-500/20",
    "security-text": "text-blue-400",
  },
  main_input: {
    background: "bg-gradient-to-r from-gray-950 to-slate-950",
    border: "border border-slate-800",
    "text-color": "text-gray-200",
  },
  account_page: {
    "container-bg": "bg-gradient-to-br from-black via-gray-950 to-black",
    "card-bg": "bg-gray-900/50",
    "card-border": "border-gray-800/30",
    "header-text": "text-yellow-300",
    "subtitle-text": "text-gray-400",
    "section-header-text": "text-yellow-200",
    "section-header-border": "border-gray-800",
    "input-bg": "bg-gradient-to-r from-gray-950 to-slate-950",
    "input-border": "border-slate-800",
    "input-text": "text-white",
    "balance-card-bg": "bg-gradient-to-br from-yellow-900/20 to-yellow-800/10",
    "balance-card-border": "border-yellow-700/30",
    "balance-label-text": "text-gray-400",
    "balance-value-text": "text-yellow-400",
    "button-primary-bg": "bg-gradient-to-r from-yellow-600 to-yellow-700",
    "button-primary-hover": "hover:from-yellow-700 hover:to-yellow-800",
    "button-primary-text": "text-black",
  },
  user_management_page: {
    "page-bg": "bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900",
    "page-text": "text-white",
    "header-icon-bg": "bg-yellow-500/10",
    "header-icon-text": "text-yellow-400",
    "header-text": "text-white",
    "subtitle-text": "text-gray-400",
    "card-bg": "bg-gray-800/50",
    "card-border": "border-gray-700/30",
    "section-header-text": "text-gray-300",
    "section-header-border": "border-gray-700",
    "column-header-bg": "bg-gray-800/50",
    "column-header-text": "text-gray-300",
    "row-hover": "hover:bg-slate-700/30",
    "row-text": "text-white",
    "row-border": "border-slate-700/30",
    "balance-text": "text-emerald-400",
    "input-bg": "bg-slate-800",
    "input-border": "border-slate-600",
    "input-text": "text-white",
    "button-primary-bg": "bg-gradient-to-r from-yellow-600 to-yellow-500",
    "button-primary-hover": "hover:from-yellow-700 hover:to-yellow-600",
    "button-primary-text": "text-black",
    "button-secondary-bg": "bg-slate-700",
    "button-secondary-hover": "hover:bg-slate-600",
    "button-secondary-text": "text-white",
    "button-action-deposit-bg": "bg-green-500/20",
    "button-action-deposit-hover": "hover:bg-green-500/30",
    "button-action-deposit-text": "text-green-400",
    "button-action-withdraw-bg": "bg-red-500/20",
    "button-action-withdraw-hover": "hover:bg-red-500/30",
    "button-action-withdraw-text": "text-red-400",
    "info-card-bg": "bg-slate-700/50",
    "info-card-border": "border-slate-600/50",
    "info-label-text": "text-gray-400",
    "info-value-text": "text-white",
    "badge-deposit-bg": "bg-green-500/20",
    "badge-deposit-text": "text-green-400",
    "badge-withdraw-bg": "bg-red-500/20",
    "badge-withdraw-text": "text-red-400",
  },
  game_options_modal: {
    "modal-border": "border-yellow-700/40",
    "header-title": "text-yellow-400",
    "header-subtitle": "text-gray-300",
    "header-vs-text": "text-yellow-500",
    "header-date-text": "text-gray-500",
    "title-text": "text-yellow-300",
    "subtitle-text": "text-gray-400",
    "market-card-bg": "bg-gray-500/10",
    "market-card-border": "border-[#DC2626]/10",
    "market-card-hover": "hover:border-[#DC2626]/20 hover:bg-[#450A0A]/20",
    "market-title": "text-gray-300",
    "axis-label-text": "text-gray-400",
    "axis-label-bg": "bg-yellow-900/20",
  },
  modal: {
    change_password: {
      "modal-bg": "bg-slate-900",
      "modal-border": "border-yellow-700",
      "modal-shadow": "shadow-yellow-900/20",
      "header-border": "border-yellow-700/50",
      "header-title": "text-yellow-400",
      "header-icon": "text-yellow-500",
      "close-button": "text-gray-400",
      "close-button-hover": "hover:text-yellow-300",
      "info-box-bg": "bg-yellow-500/10",
      "info-box-border": "border-yellow-500/20",
      "info-box-text": "text-yellow-300",
      "cancel-button-bg": "bg-slate-700",
      "cancel-button-hover": "hover:bg-slate-600",
      "cancel-button-text": "text-white",
      "confirm-button-bg": "bg-gradient-to-r from-yellow-600 to-yellow-700",
      "confirm-button-hover": "hover:from-yellow-500 hover:to-yellow-600",
      "confirm-button-text": "text-black",
      "confirm-button-shadow": "shadow-yellow-600/25",
    },
    "overlay-bg": "bg-black/50",
    "content-bg": "bg-gray-900",
    "content-border": "border-yellow-700/30",
    "header-bg": "bg-gradient-to-r from-black to-gray-900",
    "header-text": "text-yellow-100",
    "header-border": "border-yellow-700/30",
    "body-bg": "bg-transparent",
    "body-text": "text-slate-200",
    "footer-bg": "bg-black/50",
    "footer-border": "border-yellow-700/30",
    "close-button": "text-gray-400 hover:text-yellow-400",
    "close-button-hover": "hover:bg-yellow-900/40",
  },
  "bg-main": "bg-gradient-to-r from-black via-[#1a1a1a] to-black",
  "bg-secondary": "bg-gray-900",
  "bg-tertiary": "bg-gray-800",
  "bg-gradient": "bg-gradient-to-br from-gray-900 to-black",
  "bg-gradient-hover": "hover:from-gray-800 hover:to-gray-900",
  "text-primary": "text-yellow-50",
  "text-secondary": "text-yellow-100/70",
  "text-muted": "text-yellow-600",
  "text-link": "text-blue-400",
  "text-accent": "text-yellow-900/70",
  border: "border-yellow-800/50",
  "border-light": "border-yellow-300/20",
  primary: "text-yellow-500",
  "primary-bg": "bg-yellow-600",
  "card-bg": "bg-[#161616]",
  "primary-hover": "hover:bg-yellow-500",
  accent: "text-yellow-400",
  "light-divider": "bg-yellow-300/40",
  "dark-divider": "bg-gray-700",
  "accent-bg": "bg-yellow-500",
  "button-primary": "bg-yellow-600 hover:bg-yellow-500 text-black font-bold",
  "button-secondary":
    "bg-gray-800 hover:bg-gray-700 text-yellow-400 border border-yellow-700",
  card: "bg-[#161616] border-yellow-700/30",
  "card-hover": "hover:border-yellow-500/60 hover:bg-gray-900/70",
  "input-bg":
    "bg-gradient-to-r from-slate-50 to-slate-50 placeholder-slate-400 ",
  "input-border": "border-slate-400 ",
  "input-focus-within":
    "focus-within:outline-none focus-within:ring-2 focus:outline-none focus:ring-2 focus-within:ring-ring focus-within:ring-offset-0 focus-within:bg-smalltext/10 focus:ring-yellow-500/80  focus:ring-2 focus:border-yellow-500/80 focus:ring-yellow-500/80 focus-within:border-yellow-500/80 ",
  "input-ring":
    "outline-none ring-2 ring-yellow-500/80 outline-none ring-ring ring-offset-0 bg-smalltext/10 border-yellow-500/80",
  "select-option-bg":
    "bg-gradient-to-br from-yellow-800 to-yellow-900  text-white",
  "select-option-range-bg":
    "bg-yellow-700/90 text-white hover:bg-yellow-700/60",

  "input-text": "text-gray-700",
  "skeleton-bg": "bg-rose-800/20",
  "modal-bg": "bg-[#161616]",
  "button-primary-bg": "bg-gradient-to-r from-yellow-600 to-yellow-500",
  "button-primary-border": "border border-yellow-700",
  "button-primary-hover": "hover:from-yellow-700 hover:to-yellow-600",
  "button-primary-text": "text-black",
  "button-secondary-bg": "bg-[#3a3a3a]",
  "button-secondary-border": "border border-[#4a4a4a]",
  "button-secondary-hover": "hover:from-rose-800/80 hover:to-rose-900/80",
  "button-secondary-text": "text-white",
  "button-tertiary-bg": "bg-gradient-to-r from-[#2a2a2a] to-[#3a3a3a]",
  "button-tertiary-border": "border border-[#4a4a4a]",
  "button-tertiary-hover": "hover:from-[#3a3a3a] hover:to-[#4a4a4a]",
  "button-tertiary-text": "text-white",
  "item-hover-border-l": "hover:border-l-yellow-500/80",
  "button-cancel-bg": "bg-gradient-to-r from-rose-600 to-red-600",
  "button-cancel-hover": "hover:from-rose-700 hover:to-red-700",
  "button-cancel-text": "text-white",
  "button-cancel-border": "border-rose-500/80",
  "button-proceed-bg": "bg-gradient-to-r from-emerald-600 to-green-600",
  "button-proceed-hover": "hover:from-emerald-700 hover:to-green-700",
  "button-proceed-text": "text-white",
  "button-proceed-border": "border-emerald-500",
  "odds-button-bg": "bg-gray-200",
  "odds-button-hover": "hover:bg-[#F87171]",
  "odds-button-text": "text-gray-800",
  "odds-button-border": "border-gray-600/50",
  "odds-button-selected-bg":
    "bg-gradient-to-r from-[#7F1D1D] via-rose-800 to-[#7F1D1D]",
  "odds-button-selected-border": "border-[#DC2626]/70",
  "odds-button-selected-text": "text-gray-200",
  "odds-button-selected-hover": "hover:bg-[#DC2626]/30",
  "odds-button-disabled-bg": "bg-gray-100/90",
  "odds-button-disabled-text": "text-gray-800",
  "odds-button-disabled-border": "border-gray-400",

  "top-bets-bg": "bg-white",
  "top-bets-border": "border-gray-300",
  "top-bets-text-primary": "text-gray-700",
  "top-bets-text-secondary": "text-gray-500",
  "top-bets-hover": "hover:bg-gray-100",
};
